### ISSUE TITLE
save_merged_data produces loads of files

### ISSUE THREAD

**Issue by qq23840** [openghg/openghg_inversions#108]
Perhaps a silly issue exposing my lack of understanding of zarr, but when running an inversion with `save_merged_data = True`, the resulting `*_merged-data.pickle.zarr` directory contains a huge number of files (upwards of 25k, sometimes). It's not big in terms of space, but it's meant I fairly quickly run into my filenumber limit on bp1. 

I don't actually need to save the merged data, so will just set to False for now, but more generally is there a way of making these output folders contain less files? I know #92 allowed for more options in terms of the merged data, but it seems to default to this zarr format.

**Comment by brendan-m-murphy** [comment]
Each "chunk" in a zarr store is saved as a separate file. If you use `xr.open_zarr("*_merged-data.pickle.zarr")` you can see how many chunks there are (without loading the data into memory). I guess the xarray defaults might be creating a lot of chunks. I can change that.

I can make it possible to pass the output type of file used, so it could be saved as netcdf.

@gareth-j any suggestions? is this something the nested directory store helps with?

**Comment by gareth-j** [comment]
Is this cache something that needs to be updated or is it a one time thing?
If it's just cached and then read you could maybe use a ZipStore instead.

**Comment by brendan-m-murphy** [comment]
@qq23840 for now, maybe set "save_merged_data" to false, and if you want to hold onto the old data, make it into a zip file.

@gareth-j 's suggestion should fix this problem, but I might not have time to add this fix before next Thursday (I'm away until then, although I'm trying to fix some other inversions problems at the moment...)

**Comment by brendan-m-murphy** [comment]
closed by #185, which makes "zipp Zarr" the default format. (Essentially the zarr store is now zipped, and the loading code knows how to handle this.)
