### ISSUE TITLE
lognormal mean/stdev transformation doesn't work for boundary conditions

### ISSUE THREAD

**Issue by qq23840** [openghg/openghg_inversions#174]
If you want to specify a lognormal prior for the boundary conditions (not sure how often anyone wants to do this but anyway) the transformation of the parametrisation between mean/stdev and mu/sigma is not called, meaning you get an error if you specify something like:

`bcprior = {'pdf':'lognormal', 'mean':1, 'stdev':1`

Should be a pretty straightforward fix, I can have a stab now

**Comment by brendan-m-murphy** [comment]
Closed by #190
