### ISSUE TITLE
Dodgy import in `inversion_pymc.py`

### ISSUE THREAD

**Issue by qq23840** [openghg/openghg_inversions#175]
Line 18 of `inversion_pymc.py` imports the TensorVariable type, and currently reads

`from pytensor.tensor.variable import TensorVariable`

For me this throws an error, which I can fix by just changing to

`from pytensor.tensor import TensorVariable`

Is this an issue with my pytensor install? Or something everyone is getting?

**Comment by qq23840** [comment]
Applicable to people currently running inversions I suppose @brendan-m-murphy @hdelongueville @alexdanjou

**Comment by brendan-m-murphy** [comment]
It hasn't caused me problems as far as I know. It looks like pytensor.tensor's init file imports TensorVariable from pytensor.tensor.variable, so importing from pytensor.tensor will work.

**Comment by brendan-m-murphy** [comment]
Looks like this has been fixed in some previous PR
