### ISSUE TITLE
`local_influence` filter in the wrong category

### ISSUE THREAD

**Issue by qq23840** [openghg/openghg_inversions#176]
Currently, passing `local_influence` as a filter throws an error as it wasn't included in a list of filters when that was refactored I think. It doesn't require a 'site' argument, but is called in a line which passes one. 

Should be a very easy fix

**Comment by qq23840** [comment]
Actually think there's another problem, theb`local_influence` filter is holding up the whole inversion (doesn't finish inside 30 minutes, cancelled the job eventually).

**Comment by brendan-m-murphy** [comment]
Looks like this part should be changed:
``` 
                else:
                    datasets[site] = filtering_functions[filt](
                        datasets[site], site, keep_missing=keep_missing
                    )
```

I don't think any of the filters actually use the site argument (I made that change) but I forgot to change this part of the code..

**Comment by brendan-m-murphy** [comment]
I pushed a fix for the extra site parameter. Also I realised the tests for filters weren't actually doing anything... so I fixed that and made sure all of the filters get checked.

The "local_influence" filter works... I'm not sure why the performance is so bad. The test data for inversions is quite small so it probably wouldn't reveal a performance problem.
