### ISSUE TITLE
Upgrade to OpenGHG 0.8

### ISSUE THREAD

**Issue by brendan-m-murphy** [openghg/openghg_inversions#43]
Currently 0.7 is causing the tests to fail (errors in the `conftest.py` during test set up), so those will need to be fixed.

OpenGHG 0.7 also upgrades from pandas 1.53 to latest version of pandas (2.x), so we need to check if inversions still works with the latest version of pandas.

**Comment by rt17603** [comment]
@brendan-m-murphy Should we update this to Upgrade to v0.8.0 now or do we want that as a separate issue?

**Comment by brendan-m-murphy** [comment]
Closed by PR #92
