### ISSUE TITLE
Test `get_data` and running inversions separately

### ISSUE THREAD

**Issue by brendan-m-murphy** [openghg/openghg_inversions#52]
Now that there is a `get_data` function, we can test `get_data` vs. a fixed merged data file, and then use fixed merged data for the inversions tests.

The basis function wrapper could also be tested separately, and possible the post processing code.

**Comment by pearson01** [comment]
Getting an error when trying to run an inversion with the example ini file. The `get_data` function can't seem to find obs data (TAC, ch4) which is preventing the `combined_scenario` from being created. The error message is:

`UnboundLocalError: local variable 'scenario_combined' referenced before assignment`

@brendan-m-murphy

**Comment by EricSaboya** [comment]
The error @pearson01 found should now be fixed in the `update get obs` branch

**Comment by brendan-m-murphy** [comment]
I'm guessing the fix was the part that throws an error if all of the sites are dropped?

I'll make sure to add some test cases where some/all data can't be found.

**Comment by EricSaboya** [comment]
Exactly! I just added an if statement to exit the process if no site data are found before it gets to the line with `scenario_combined.mf.units`, which was what was raising this error

**Comment by brendan-m-murphy** [comment]
This was closed by PR #73
