### ISSUE TITLE
Specifying bc_basis_directory as an input from the .ini file

### ISSUE THREAD

**Issue by dangrosvenor** [openghg/openghg_inversions#6]
The utils.bc_sensitivity functions accepts bc_basis_directory as an optional input, but the main code is not currently written to accept bc_basis_directory as an input from the .ini file – this would be useful for non-Bristol people who have to specify a path for this.

**Comment by EricSaboya** [comment]
'bc_basis_directory' has now been included as an input option in the OpenGHG Inversions input file. If a path is not provided then the HBMCMC code will default to look in ~/openghg_inversions/ for a directory with the name 'bc_basis_functions' and create this directory if it is not found.
