### ISSUE TITLE
specify the directory of country-EUROPE-UKMO-landsea-2023.nc in _weighted.py

### ISSUE THREAD

**Issue by hdelongueville** [openghg/openghg_inversions#99]
The **line 14** in [openghg_inversions/openghg_inversions/basis/algorithms/**_weighted.py**, branch Iss55-fix-outer-regions] should specify the whole path of country-EUROPE-UKMO-landsea-2023.nc.

For now it is:

landsea_indices = xr.open_dataset("../countries/country-EUROPE-UKMO-landsea-2023.nc")

and should be changed to:

landsea_indices = xr.open_dataset("/group/chem/acrg/LPDM/countries/country-EUROPE-UKMO-landsea-2023.nc")

to avoid error like, for example,

FileNotFoundError: [Errno 2] No such file or directory: '/user/home/qq24644/countries/country-EUROPE-UKMO-landsea-2023.nc')

**Comment by brendan-m-murphy** [comment]
Sorry I just noticed this. To work in different settings, we probably need this to point to a path inside of openghg inversions, and have the file there (e.g. the default country file location is `openghg_inversions/countries`), or allow a path to be passed in.

The first option, combined with distributing the file with openghg inversions might be simplest.

**Comment by brendan-m-murphy** [comment]
This is related to issue #56.

**Comment by brendan-m-murphy** [comment]
It looks like this is fixed by PR #101. I'll either split that fix out or just get that PR merged in soon.
